### ISSUE TITLE
Program breaks when entering BSSID

### ISSUE THREAD

**Issue by L-E-iT** [moha99sa/EvilAP_Defender#1]
Programs breaks when entering in a BSSID from option 2 in the learning menu.  

http://imgur.com/a/QYAso

Here is an image of the error I am getting.  It is a bit unclear as to what exactly is going wrong.  I attempted to enter the BSSID a multitude of ways but none of them worked.

Any help would be appreciated on it, thanks.

**Comment by L-E-iT** [comment]
Accidently closed... should still be open

**Comment by moha99sa** [comment]
Hello L-E-iT,

Sorry, I have been busy lately. 
I will check and return to you soon :)

**Comment by moha99sa** [comment]
Hello L-E-iT,

I have resolved the issue. It was due to the recent changes in Python. I had to change the way I pass parameters to the Cursor method.

It is working fine now :)

Have fun,
