### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by tsale** [moha99sa/EvilAP_Defender#2]
It crashes every time you input the information in learning mode.  It shows the below error:

Unexpected error in 'LearningMode': <type 'exceptions.TypeError'>.

Can the creators help us sort this out. Its such a useful tool, its a shame not to be able to get it working.

**Comment by adskimomo** [comment]
Same here running on OpenWRT entering bssid or changing options gives <type 'exception. typeError'>

**Comment by moha99sa** [comment]
Hello Guys,

Sorry, I have been busy lately, so I didn't have a chance to check these issues.
I believe the reason behind these issues is the latest changes in Aircrack-ng or Kali2.
I will check and return to you soon.

**Comment by gentoo-installer** [comment]
Hi

I get the exact same error.
Could you give it a look and tell us what the problem could be ? From what i can tell is the cursor.execute has a problem with the select * from ssids where ssid=%s
I would like to help if it is possible.
Just let me know how i can, i don't really have python coding experience but still trying to fix the script :)
I will let you know if i find something.

**Comment by moha99sa** [comment]
Hello Guys,
I have solved the issue :)
It seems that there were some changes on latest versions of Python. At least in the cursor method. I have to pass the parameters as a list not as a single parameter.

Have fun :)

**Comment by devfx11** [comment]
I can't see no new version of the program.
Or its not yet commited ? :)
